maintainer       "VMware"
maintainer_email "support@vmware.com"
license          "Apache 2.0"
description      "Installs/Configures Cloud Controller"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.0.1"

depends          "service_lifecycle"
depends          "deployment"
depends          "uaa"
depends          "service_broker"
depends          "python"
depends          "erlang"
depends          "java7"
depends          "node"
depends          "redis"
depends          "ruby"